/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 SpiderMan.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Bloom, EffectComposer, Outline, Select, Selection, SelectiveBloom } from '@react-three/postprocessing'

export function SpiderMan(props) {
  const { nodes, materials } = useGLTF('/model/SpiderMan.glb')

  useEffect(() => {
    ;[nodes].forEach((node) => (node.frustumCulled = false))
  }, [nodes])

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Ch��o_0'].geometry}
        material={materials.material}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_1'].geometry}
        material={materials.Predios_Planos}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_2'].geometry}
        material={materials.material_3}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_4'].geometry}
        material={materials.material_5}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_5'].geometry}
        material={materials.material_6}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_6'].geometry}
        material={materials.material_7}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_7'].geometry}
        material={materials.material_8}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_8'].geometry}
        material={materials.Madeira_Trilho}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_8001'].geometry}
        material={materials.Madeira_Trilho}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        geometry={nodes['Ch��o_9'].geometry}
        material={materials.Ferro_Trilhos}
        position={[-1.09, -27.532, 56.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
      <mesh
        castShadow
        geometry={nodes.Cylinder001_0.geometry}
        material={materials.Acessorios}
        position={[-1.09, -0.798, 11.156]}
        rotation={[-1.563, -0.052, -0.004]}
        scale={0.011}
      >
        <meshStandardMaterial {...materials.Acessorios} />
      </mesh>
      <Selection>
        {/* <SelectiveBloom  luminanceThreshold={0} luminanceSmoothing={0.3} height={400}/> */}
        <Select enabled>
          <mesh
            castShadow
            geometry={nodes.Cylinder002_0.geometry}
            material={materials.Acessorios}
            position={[-0.817, -0.706, 11.307]}
            rotation={[-1.58, -0.075, -0.144]}
            scale={0.011}
          >
            <meshStandardMaterial {...materials.Acessorios} />
          </mesh>
        </Select>
      </Selection>

      <mesh
        geometry={nodes.Cylinder003_0.geometry}
        material={materials.Acessorios}
        position={[-1.424, -0.669, 11.172]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
        castShadow
      >
        <meshStandardMaterial {...materials.Acessorios} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder004_0.geometry}
        material={materials.Acessorios}
        position={[-1.09, -0.628, 11.466]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
        castShado
      >
        <meshStandardMaterial {...materials.Acessorios} />
      </mesh>
      <mesh
        geometry={nodes.NuvemDeVidro_0.geometry}
        material={materials.Vidro}
        position={[-0.584, 0.815, 13.679]}
        rotation={[1.473, -0.215, 1.143]}
        scale={0.011}
      />
      <group position={[0, 0.2, 0]}>
        <mesh
          geometry={nodes.Janelas001_0.geometry}
          frustumCulled={false}
          material={materials.Vidro}
          position={[0.391, 0.834, 22.822]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.Janelas008_0.geometry}
          frustumCulled={false}
          material={materials.Vidro}
          position={[-3.078, 0.834, -63.962]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.Janelas_0.geometry}
          frustumCulled={false}
          material={materials.Vidro}
          position={[0.451, 0.854, 13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        />
        <mesh
          receiveShadow
          geometry={nodes.Trem002_0.geometry}
          frustumCulled={false}
          material={materials.Trem}
          position={[-1.09, -0.848, 0.958]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes['Corrim��es001_0'].geometry}
          material={materials.Corrimos}
          position={[-1.09, -0.848, 21.301]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        />
        <mesh
          geometry={nodes.Cadeira_HR_0.geometry}
          material={materials.Cadeira}
          position={[-0.136, -0.848, 12.36]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        ></mesh>
        <group position={[1.172, -0.493, 12.9]} rotation={[-1.581, -0.557, -1.633]} scale={1.066}>
          <mesh
            geometry={nodes.sv_doctoroctopus01_s03_01_sv_doctoroctopus01_s03_01_0001_1.geometry}
            material={materials['sv_doctoroctopus01_s03_01.003']}
          />
          <mesh
            geometry={nodes.sv_doctoroctopus01_s03_01_sv_doctoroctopus01_s03_01_0001_2.geometry}
            material={materials['sv_doctoroctopus01_s03_03.003']}
          />
          <mesh
            geometry={nodes.sv_doctoroctopus01_s03_01_sv_doctoroctopus01_s03_01_0001_3.geometry}
            material={materials['sv_doctoroctopus01_s03_04.003']}
          />
          <mesh
            geometry={nodes.sv_doctoroctopus01_s03_01_sv_doctoroctopus01_s03_01_0001_4.geometry}
            material={materials['sv_doctoroctopus01_s03_02.003']}
          />
        </group>
        <group>
          <mesh
            castShadow
            geometry={nodes.Mesh_0001rip_Spiderman_Boots_D_0001.geometry}
            material={materials['Spiderman_Boots_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes['Mesh_0002rip_Spiderman_Web_D_(1)_0'].geometry}
            material={materials['Spiderman_Web_D_1.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes.Mesh_0003rip_Spiderman_Hands_D_0001.geometry}
            material={materials['Spiderman_Hands_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes.Mesh_0004rip_Spiderman_Lens_D_0001.geometry}
            material={materials['Spiderman_Web_D_1.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes.Mesh_0005rip_Spiderman_Web_D_0001.geometry}
            material={materials['Spiderman_Web_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes.Mesh_0006rip_Spiderman_Head_D_0001.geometry}
            material={materials['Spiderman_Head_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes.Mesh_0007rip_Spiderman_Torso_D_0001.geometry}
            material={materials['Spiderman_Torso_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          />
          <mesh
            castShadow
            geometry={nodes['Mesh_0008rip_Spiderman_Web_D_(2)_0'].geometry}
            material={materials['Spiderman_Web_D_2.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          >
            {/* <meshStandardMaterial {...materials['Spiderman_Web_D_2.001']} toneMapped={false} color={[69, 71, 74]} /> */}
          </mesh>

          <mesh
            castShadow
            geometry={nodes.Mesh_0009rip_Spiderman_Web_D_0001.geometry}
            material={materials['Spiderman_Web_D.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          >
            {/* <meshStandardMaterial {...materials['Spiderman_Web_D.001']} toneMapped={false} color={[69, 71, 74]} /> */}
          </mesh>

          <mesh
            castShadow
            geometry={nodes['Mesh_0000rip_Spiderman_Torso_D_(1)_0'].geometry}
            material={materials['Spiderman_Torso_D_1.001']}
            position={[-0.634, -0.386, 12.842]}
            rotation={[1.574, 0.259, -1.627]}
            scale={1.202}
          >
            <meshStandardMaterial {...materials['Spiderman_Torso_D_1.001']} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SpiderMan.glb')
